/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationRouteImport } from './routes/location'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SourceSystemRouteImport } from './routes/source-system'
import { Route as LocationIndexRouteImport } from './routes/location.index'
import { Route as LocationLocationIdRouteImport } from './routes/location.$locationId'
import { Route as LocationCreateRouteImport } from './routes/location.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceSystemRoute = SourceSystemRouteImport.update({
  id: '/source-system',
  path: '/source-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationRoute,
} as any)
const LocationLocationIdRoute = LocationLocationIdRouteImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => LocationRoute,
} as any)
const LocationCreateRoute = LocationCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LocationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/location': typeof LocationRouteWithChildren
  '/master-data': typeof MasterDataRoute
  '/site': typeof SiteRoute
  '/source-system': typeof SourceSystemRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/location/create': typeof LocationCreateRoute
  '/location/': typeof LocationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/master-data': typeof MasterDataRoute
  '/site': typeof SiteRoute
  '/source-system': typeof SourceSystemRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/location/create': typeof LocationCreateRoute
  '/location': typeof LocationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/location': typeof LocationRouteWithChildren
  '/master-data': typeof MasterDataRoute
  '/site': typeof SiteRoute
  '/source-system': typeof SourceSystemRoute
  '/location/$locationId': typeof LocationLocationIdRoute
  '/location/create': typeof LocationCreateRoute
  '/location/': typeof LocationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/location'
    | '/master-data'
    | '/site'
    | '/source-system'
    | '/location/$locationId'
    | '/location/create'
    | '/location/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/master-data'
    | '/site'
    | '/source-system'
    | '/location/$locationId'
    | '/location/create'
    | '/location'
  id:
    | '__root__'
    | '/'
    | '/location'
    | '/master-data'
    | '/site'
    | '/source-system'
    | '/location/$locationId'
    | '/location/create'
    | '/location/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocationRoute: typeof LocationRouteWithChildren
  MasterDataRoute: typeof MasterDataRoute
  SiteRoute: typeof SiteRoute
  SourceSystemRoute: typeof SourceSystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-system': {
      id: '/source-system'
      path: '/source-system'
      fullPath: '/source-system'
      preLoaderRoute: typeof SourceSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/'
      fullPath: '/location/'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof LocationRoute
    }
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdRouteImport
      parentRoute: typeof LocationRoute
    }
    '/location/create': {
      id: '/location/create'
      path: '/create'
      fullPath: '/location/create'
      preLoaderRoute: typeof LocationCreateRouteImport
      parentRoute: typeof LocationRoute
    }
  }
}

interface LocationRouteChildren {
  LocationLocationIdRoute: typeof LocationLocationIdRoute
  LocationCreateRoute: typeof LocationCreateRoute
  LocationIndexRoute: typeof LocationIndexRoute
}

const LocationRouteChildren: LocationRouteChildren = {
  LocationLocationIdRoute: LocationLocationIdRoute,
  LocationCreateRoute: LocationCreateRoute,
  LocationIndexRoute: LocationIndexRoute,
}

const LocationRouteWithChildren = LocationRoute._addFileChildren(
  LocationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocationRoute: LocationRouteWithChildren,
  MasterDataRoute: MasterDataRoute,
  SiteRoute: SiteRoute,
  SourceSystemRoute: SourceSystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
